// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sezjdoxxpsjhnpbuypmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlempkb3h4cHNqaG5wYnV5cG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjU1NjksImV4cCI6MjA2MTQwMTU2OX0.BA8J6rEHs7XxTgKUX5_dYM3xloAFJR39nFHyKApVgA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);